=== colorer/Colorer-schemes/src/hrc/src/yml/src/shops.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT yml_catalog (shop)>
<!ATTLIST yml_catalog
        date CDATA #REQUIRED>

<!ELEMENT shop (name, company, url, phone?, platform?, version?, agency?, email*, currencies, categories, delivery-options?, store?, pickup?, delivery?, deliveryIncluded?, local_delivery_cost?, adult?, offers, gifts?, promos?)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT phone (#PCDATA)>

<!ELEMENT currencies (currency+)>
<!ELEMENT currency EMPTY>
<!ATTLIST currency
        id (RUR|RUB|USD|BYN|BYR|KZT|EUR|UAH) #REQUIRED
        rate CDATA "1"
        plus CDATA "0">


<!ELEMENT categories (category+)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST category
        id CDATA #REQUIRED
        parentId CDATA #IMPLIED
        tid CDATA #IMPLIED
        yid CDATA #IMPLIED>

<!ELEMENT delivery-options (option+)>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
        cost CDATA #REQUIRED
        days CDATA #REQUIRED
        order-before CDATA #IMPLIED>

<!ELEMENT offers (offer+)>
<!ELEMENT offer (url?, buyurl?, shop-sku?, price, oldprice?, wprice?, purchase_price?, currencyId, xCategory?, categoryId+, market_category?,
        picture*, store?, pickup?, delivery?, deliveryIncluded?, ((local_delivery_cost?, orderingTime?)|(delivery-options?))?,
        ((typePrefix?, vendor, vendorCode?, model, (provider, tarifplan?)?) |
                (author?, name, publisher?, series?, year?, ISBN?, volume?, part?, language?, binding?, page_extent?, table_of_contents?) |
                (author?, name, publisher?, series?, year?, ISBN?, volume?, part?, language?, table_of_contents?, performed_by?, performance_type?, storage?, format?, recording_length?) |
                (artist?, title, year?, media?, starring?, director?, originalName?, country?) |
                (worldRegion?, country?, region?, days, dataTour*, name, hotel_stars?, room?, meal?, included, transport, price_min?, price_max?, options?) |
                (name, place, hall?, hall_part?, date, is_premiere?, is_kids?) |
                (name, vendor?, vendorCode?)
                ),
        aliases?, additional*, description?, sales_notes?,min-quantity?,step-quantity?,
        manufacturer_warranty?,seller_warranty?, country_of_origin?, downloadable?, adult?,
        age?,
        barcode*,
        expiry?,
        weight?,
        dimensions?,
        condition?,
        param*,
        related_offer*
        )>
<!ATTLIST offer
        id CDATA #IMPLIED
        group_id CDATA #IMPLIED
        type (vendor.model | book | medicine | audiobook | artist.title | tour | ticket | event-ticket) #IMPLIED
        available (true | false) #IMPLIED
        bid CDATA #IMPLIED>

<!ELEMENT promos (promo+)>

<!ELEMENT promo (
        start-date?,end-date?,description?,url?,promo-code?,discount?,purchase,promo-gifts?
        )>
<!ATTLIST promo
        id CDATA #REQUIRED
        type CDATA #REQUIRED>
<!ELEMENT purchase (required-quantity?,free-quantity?,product+)>
<!ELEMENT promo-gifts (promo-gift+)>

<!ELEMENT discount (#PCDATA)>
<!ATTLIST discount
        unit (percent|currency) #IMPLIED
        currency CDATA #IMPLIED>

<!ELEMENT product (discount-price?)>
<!ATTLIST product
        offer-id CDATA #IMPLIED
        category-id CDATA #IMPLIED
        >


<!ELEMENT discount-price (#PCDATA)>
<!ATTLIST discount-price
        currency CDATA #IMPLIED>
<!ELEMENT promo-gift EMPTY>
<!ATTLIST promo-gift
        offer-id CDATA #IMPLIED
        gift-id CDATA #IMPLIED
        >

<!ELEMENT gifts (gift+)>
<!ELEMENT gift (name,picture)>
<!ATTLIST gift
        id CDATA #IMPLIED
        >
<!ELEMENT start-date (#PCDATA)>
<!ELEMENT end-date (#PCDATA)>
<!ELEMENT promo-code (#PCDATA)>
<!ELEMENT required-quantity (#PCDATA)>
<!ELEMENT free-quantity (#PCDATA)>

<!ELEMENT url (#PCDATA)>
<!ELEMENT store (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT platform (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT agency (#PCDATA)>
<!ELEMENT buyurl (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT pickup (#PCDATA)>
<!ELEMENT delivery (#PCDATA)>
<!ELEMENT deliveryIncluded EMPTY>
<!ELEMENT local_delivery_cost (#PCDATA)>
<!ELEMENT orderingTime (onstock?, ordering, deliveryTime?)>
<!ELEMENT onstock EMPTY>
<!ELEMENT ordering (#PCDATA)>
<!ATTLIST ordering
        hours CDATA #IMPLIED>

<!ELEMENT deliveryTime EMPTY>
<!ELEMENT shop-sku (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT oldprice (#PCDATA)>
<!ELEMENT purchase_price (#PCDATA)>
<!ELEMENT wprice (#PCDATA)>
<!ELEMENT currencyId (#PCDATA)>
<!--<!ELEMENT vat (#PCDATA)>-->
<!ELEMENT categoryId (#PCDATA)>
<!ATTLIST categoryId
        type (Yandex | Torg | Own) "Own" >

<!ELEMENT market_category (#PCDATA)>
<!ELEMENT typePrefix (#PCDATA)>
<!ELEMENT vendor (#PCDATA)>
<!ELEMENT vendorCode (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT part (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT binding (#PCDATA)>
<!ELEMENT page_extent (#PCDATA)>
<!ELEMENT table_of_contents (#PCDATA)>
<!ELEMENT performed_by (#PCDATA)>
<!ELEMENT performance_type (#PCDATA)>
<!ELEMENT storage (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT recording_length (#PCDATA)>
<!ELEMENT series (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT media (#PCDATA)>
<!ELEMENT starring (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT originalName (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT sales_notes (#PCDATA)>
<!ELEMENT min-quantity (#PCDATA)>
<!ELEMENT step-quantity (#PCDATA)>
<!ELEMENT aliases (#PCDATA)>
<!ELEMENT provider (#PCDATA)>
<!ELEMENT tarifplan (#PCDATA)>
<!ELEMENT xCategory (#PCDATA)>
<!ELEMENT additional (#PCDATA)>
<!ELEMENT worldRegion (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT days (#PCDATA)>
<!ELEMENT dataTour (#PCDATA)>
<!ELEMENT hotel_stars (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ELEMENT meal (#PCDATA)>
<!ELEMENT included (#PCDATA)>
<!ELEMENT transport (#PCDATA)>
<!ELEMENT price_min (#PCDATA)>
<!ELEMENT price_max (#PCDATA)>
<!ELEMENT options (#PCDATA)>
<!ELEMENT manufacturer_warranty (#PCDATA)>
<!ELEMENT seller_warranty (#PCDATA)>
<!ELEMENT country_of_origin (#PCDATA)>
<!ELEMENT downloadable (#PCDATA)>
<!ELEMENT adult (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ATTLIST age
        unit (month|year) "year">
<!ELEMENT expiry (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT dimensions (#PCDATA)>
<!ELEMENT barcode (#PCDATA)>
<!--<!ELEMENT cpa (#PCDATA)>-->
<!--<!ELEMENT rec (#PCDATA)>-->
<!ELEMENT condition (reason)>
<!ATTLIST condition
    type (likenew|used) #REQUIRED>
<!ELEMENT reason (#PCDATA)>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param
        name CDATA #REQUIRED
        unit CDATA #IMPLIED>
<!ELEMENT related_offer (#PCDATA)>

<!ELEMENT place (#PCDATA)>
<!ELEMENT hall (#PCDATA)>
<!ATTLIST hall
        plan CDATA #IMPLIED>

<!ELEMENT hall_part (#PCDATA)>
<!ELEMENT is_premiere (#PCDATA)>
<!ELEMENT is_kids (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== colorer/Colorer-schemes/tests/test/xml/full/yml.xml
<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE yml_catalog SYSTEM "shops.dtd">

<yml_catalog date="2000-11-16 20:17">
<shop>
  <name>BestShop</name>
  <company>Best online seller Inc.</company>
  <url>http://best.seller.ru/</url>

<currencies>
  <currency id="RUR" rate="1"/>

  <currency id="USD" rate="23.98"/>
  <currency id="EUR" rate="36.25"/>
  <currency id="UAH" rate="5.6"/>
</currencies>

<categories>
  <category id="1">Книги</category>

  <category id="2">Видео</category>
  <category id="3" parentId="1">Детективы</category>
  <category id="4" parentId="1">Боевики</category>
  <category id="5" parentId="2">Комедии</category>

  <category id="6">Принтеры</category>
  <category id="7">Оргтехника</category>
</categories>
<offers>
<offer id="12341" type="vendor.model" available="true" bid="13">

  <url>http://best.seller.ru/product_page.asp?pid=12344</url>
  <price>700</price>
  <currencyId>USD</currencyId>
  <categoryId> 6 </categoryId>
  <picture>http://best.seller.ru/img/device12345.jpg</picture>
  <delivery> true </delivery>
  <typePrefix> Принтер </typePrefix>
  <vendor> НP </vendor>
  <vendorCode> Q7533A </vendorCode>
  <model> Color LaserJet 3000</model>
  <description>
    A4, 64Mb, 600x600 dpi, USB 2.0, 29стр/мин ч/б / 15стр/мин цв, лотки на 100л и 250л, плотность до 175г/м, до 60000 стр/месяц
  </description>
  <manufacturer_warranty>true</manufacturer_warranty>
  <country_of_origin>Япония</country_of_origin>
 
</offer>
<offer id="12346" available="true" bid="21">
  <url>http://best.seller.ru/product_page.asp?pid=12348</url>

  <price>699.54</price>
  <currencyId>USD</currencyId>
  <categoryId>6</categoryId>
  <picture>http://best.seller.ru/img/device12345.jpg</picture>
  <delivery>false</delivery>
  <name> Золотые наручные часы </name>
  <vendorCode> A1234567B </vendorCode>
  <description> Изящные золотые часы.</description>
  <country_of_origin>Китай</country_of_origin>

</offer>
<offer id="12342" type="book" available="true" bid="17">
  <url>http://best.seller.ru/product_page.asp?pid=14345</url>
  <price>80</price>
  <currencyId>RUR</currencyId>

  <categoryId>3</categoryId>
  <picture>http://best.seller.ru/product_page.asp?pid=14345.jpg</picture>
  <delivery>true</delivery>
  <author>Александра Маринина</author>
  <name>Все не так. В 2 томах. Том 1</name>

  <publisher>ЭКСМО - Пресс</publisher>
  <series>А. Маринина - королева детектива</series>
  <year>2007</year>
  <ISBN>978-5-699-23647-3</ISBN>
  <volume>2</volume>
  <part>1</part>
  <language>rus </language>
  <binding>70x90/32</binding>
  <page_extent>288</page_extent>

  <description>
Все прекрасно в большом патриархальном семействе Руденко. Но - увы! - 
впечатление это обманчиво: каждого из многочисленных (еще)Все прекрасно в 
большом патриархальном семействе Руденко. Но - увы! - впечатление это обманчиво:
 каждого из многочисленных представителей семьи обуревают свои потаенные страсти
 и запретные желания. И потому, когда погибает, причем явно.
  </description>

  <downloadable>false</downloadable>

</offer>
<offer id="12345" type="artist.title" available="true" bid="11">

  <url>http://best.seller.ru/product_page.asp?pid=12946</url>
  <price>150</price>
  <currencyId>USD</currencyId>
  <categoryId>2</categoryId>

    <picture>http://best.seller.ru/product_page.asp?pid=14345.jpg</picture>
  <delivery>true</delivery>
  <artist>Pink Floyd</artist>
  <title>Dark Side Of The Moon, Platinum Disc</title>
  <year>1999</year>

  <media>CD</media>

<description> Dark Side Of The Moon, поставивший мир на уши
 невиданным сочетанием звуков, - это всего-навсего девять 
треков, и даже не все они писались специально для альбома. 
Порывшись по сусекам, участники Pink Floyd мудро сделали 
новое из хорошо забытого старого - песен, которые 
почему-либо не пошли в дело или остались незаконченными. 
Одним из источников вдохновения стали саундтреки 
для кинофильмов, которые группа производила в больших количествах.

</description>


</offer>

<offer id="12344" type="artist.title" available="true" bid="56">
  <url>http://best.seller.ru/product_page.asp?pid=92347</url>

  <price>93</price>
  <currencyId>RUR</currencyId>
  <categoryId>2</categoryId>
  <picture>http://best.seller.ru/img/device92347.jpg</picture>
  <delivery>true</delivery>
  <title>Свадьба Мюриэл</title>
  <year>1999</year>
  <media>DVD</media>
  <starring>Тони Колетт (Toni Collette), Рэйчел Грифитс (Rachel Griffiths)</starring>

  <director>П Дж Хоген</director>
  <originalName>Muriel's wedding</originalName>
  <country>Австралия</country>
  <description> 
Гадкий утенок из провинциального городка покидает свое 
гнездо, и в компании своей подруги отправляется искать веселой жизни в большой и
 загадочный город. Фильм о мечтах и реальности, дружбе и юности молодой девушки,    
 приключения которой повторяют судьбы Золушки и героини Джулии Робертс из 
ставшего классикой фильма Красотка...
  </description>

</offer>

<offer id="12341" type="tour" available="true" bid="71">
  <url>http://best.seller.ru/product_page.asp?pid=12344</url>
  <price>958</price>

  <currencyId>USD</currencyId>
  <categoryId>6</categoryId>
  <picture>http://best.seller.ru/img/device12345.jpg</picture>
  <delivery>false</delivery>
  <worldRegion>Африка</worldRegion>

  <country>Египет</country>
  <region>Хургада</region>
  <days>7</days>
  <dataTour>01/01/03</dataTour>

  <dataTour>08/01/03</dataTour>
  <name>Hilton</name>
  <hotel_stars>5*****</hotel_stars>
  <room>SNG</room>

  <meal>ALL</meal>
  <included>авиаперелет, трансфер, проживание, питание, страховка</included>
  <transport>Авиа</transport>
  <description></description>

</offer>

 <offer id="1234" type="event-ticket"  available="true" bid="13"> 
 <url>url товарного предложения</url>
 <price>100000</price>
 <currencyId>RUR</currencyId>
 <categoryId>3</categoryId> 
 <picture>url картинки товарного предложения</picture>
 <delivery>true</delivery>
 <name>Дмитрий Хворостовский и Национальный филармонический
 оркестр России. Дирижер - Владимир Спиваков.</name>
 <place>Московский  международный Дом музыки</place>
 <hall plan="url плана зала">Большой  зал</hall>
 <hall_part>Партер р. 1-5</hall_part>

 <date>2004-12-31T19:00</date> 
 <is_premiere>0</is_premiere>
 <is_kids>0</is_kids>
 <description>описание товарного предложения.</description>

</offer>

 <offer id="107" type="vendor.model" bid="23" cbid="43" available="true">
   <url>http://</url>
   <price>55</price>
   <currencyId>USD</currencyId>

   <categoryId>35</categoryId>
   <picture>http://</picture>
   <delivery>false</delivery>   
   <typePrefix>Наушники</typePrefix>
   <vendor>SONY</vendor>

   <model>MDR-CD480</model>
   <description> </description>
  </offer>

    <offer id="107" type="vendor.model" bid="15" available="true">
   <url>http://</url>

   <price>55</price>
   <currencyId>USD</currencyId>
   <categoryId>35</categoryId>
   <picture>http://</picture>
   <delivery>true</delivery>
   <typePrefix>Наушники</typePrefix>
   <vendor>SONY</vendor>
   <model>MDR-CD480</model>
   <description> </description>

  </offer>

   <offer id="107" type="vendor.model" cbid="25" available="true">
   <url>http://</url>

   <price>55</price>
   <currencyId>USD</currencyId>
   <categoryId>35</categoryId>
   <picture>http://</picture>
   <delivery>true</delivery>   
   <typePrefix>Наушники</typePrefix>
   <vendor>SONY</vendor>
   <model>MDR-CD480</model>
   <description> </description>

  </offer>

</offers>

</shop>
</yml_catalog>
